---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: saucy-server-cloudimg-amd64
    driver_config:
      box: saucy-server-cloudimg-amd64

suites:
  - name: default
    run_list:
      - recipe[initial::default]
    attributes:
