---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-1404
    driver_config:
      box: trusty-14.04-cloudimg-i386

suites:
  - name: default
    run_list:
      - recipe[initial::default]
    attributes:
